// Code generated by candi v1.14.3.

package resthandler

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/labstack/echo"

	"PLTD3/internal/modules/distribution/domain"
	"PLTD3/pkg/shared/usecase"

	"github.com/golangid/candi/candihelper"
	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Mount handler with root "/"
// handling version in here
func (h *RestHandler) Mount(root *echo.Group) {
	v1Root := root.Group(candihelper.V1)

	distribution := v1Root.Group("/distribution", echo.WrapMiddleware(h.mw.HTTPBearerAuth))
	distribution.GET("", h.getAllDistribution, echo.WrapMiddleware(h.mw.HTTPPermissionACL("getAllDistribution")))
	distribution.GET("/:instansi", h.getDistributionByInstansi, echo.WrapMiddleware(h.mw.HTTPPermissionACL("getDistributionByInstansi")))
	distribution.GET("/sum", h.getSumDistribution, echo.WrapMiddleware(h.mw.HTTPPermissionACL("getSumDistribution")))

	// hapus jika tidak perlu
	// distribution.GET("/:id", h.getDetailDistributionByID, echo.WrapMiddleware(h.mw.HTTPPermissionACL("getDetailDistribution")))
	// distribution.POST("", h.createDistribution, echo.WrapMiddleware(h.mw.HTTPPermissionACL("createDistribution")))
	// distribution.PUT("/:id", h.updateDistribution, echo.WrapMiddleware(h.mw.HTTPPermissionACL("updateDistribution")))
	// distribution.DELETE("/:id", h.deleteDistribution, echo.WrapMiddleware(h.mw.HTTPPermissionACL("deleteDistribution")))
}


func (h *RestHandler) getSumDistribution(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "DistributionDeliveryREST:GetSumDistribution")
	defer trace.Finish()

	
	var filter domain.FilterDistribution
	if err := candihelper.ParseFromQueryParam(c.Request().URL.Query(), &filter); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(c.Response())
	}

	data, err := h.uc.Distribution().GetSumDistribution(ctx, &filter)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success", data).JSON(c.Response())
}

func (h *RestHandler) getAllDistribution(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "DistributionDeliveryREST:GetAllDistribution")
	defer trace.Finish()

	tokenClaim := candishared.ParseTokenClaimFromContext(ctx) // must using HTTPBearerAuth in middleware for this handler

	var filter domain.FilterDistribution
	if err := candihelper.ParseFromQueryParam(c.Request().URL.Query(), &filter); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(c.Response())
	}

	// ini dikomen dlu
	// if err := h.validator.ValidateDocument("distribution/get_all", filter); err != nil {
	// 	return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate filter", err).JSON(c.Response())
	// }

	data, meta, err := h.uc.Distribution().GetAllDistribution(ctx, &filter)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	message := "Success, with your user id (" + tokenClaim.Subject + ") and role (" + tokenClaim.Role + ")"
	return wrapper.NewHTTPResponse(http.StatusOK, message, meta, data).JSON(c.Response())
}

func (h *RestHandler) getDistributionByInstansi(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "DistributionDeliveryREST:GetDistributionByInstansi")
	defer trace.Finish()

	var filter domain.FilterDistribution
	if err := candihelper.ParseFromQueryParam(c.Request().URL.Query(), &filter); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(c.Response())
	}

	fmt.Println("satu", c.Param("instansi"))
	data, meta, err := h.uc.Distribution().GetDistributionByInstansi(ctx, c.Param("instansi"), &filter)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success", meta, data).JSON(c.Response())
}


// hapus jika gak perlu

func (h *RestHandler) getDetailDistributionByID(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "DistributionDeliveryREST:GetDetailDistributionByID")
	defer trace.Finish()

	data, err := h.uc.Distribution().GetDetailDistribution(ctx, c.Param("id"))
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success", data).JSON(c.Response())
}

func (h *RestHandler) createDistribution(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "DistributionDeliveryREST:CreateDistribution")
	defer trace.Finish()

	body, _ := io.ReadAll(c.Request().Body)
	if err := h.validator.ValidateDocument("distribution/save", body); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(c.Response())
	}

	var payload domain.RequestDistribution
	if err := json.Unmarshal(body, &payload); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	err := h.uc.Distribution().CreateDistribution(ctx, &payload)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusCreated, "Success").JSON(c.Response())
}

func (h *RestHandler) updateDistribution(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "DistributionDeliveryREST:UpdateDistribution")
	defer trace.Finish()

	body, _ := io.ReadAll(c.Request().Body)
	if err := h.validator.ValidateDocument("distribution/save", body); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(c.Response())
	}

	var payload domain.RequestDistribution
	if err := json.Unmarshal(body, &payload); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	payload.ID = c.Param("id")
	err := h.uc.Distribution().UpdateDistribution(ctx, &payload)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success").JSON(c.Response())
}

func (h *RestHandler) deleteDistribution(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "DistributionDeliveryREST:DeleteDistribution")
	defer trace.Finish()

	if err := h.uc.Distribution().DeleteDistribution(ctx, c.Param("id")); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success").JSON(c.Response())
}
