// Code generated by candi v1.14.3.

package repository

import (
	"context"

	"time"

	"github.com/google/uuid"

	"PLTD3/internal/modules/kpi/domain"
	shareddomain "PLTD3/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"PLTD3/pkg/shared"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type kpiRepoSQL struct {
	readDB, writeDB *gorm.DB
}

// NewKpiRepoSQL mongo repo constructor
func NewKpiRepoSQL(readDB, writeDB *gorm.DB) KpiRepository {
	return &kpiRepoSQL{
		readDB, writeDB,
	}
}

func (r *kpiRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterKpi) (data []shareddomain.Kpi, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "KpiRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}
	
	err = r.setFilterKpi(shared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	}).Limit(filter.Limit).Offset(filter.CalculateOffset()).Find(&data).Error
	return
}

func (r *kpiRepoSQL) FetchAllEaf(ctx context.Context, filter *domain.FilterKpi) (data []shareddomain.Kpi, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "KpiRepoSQL:FetchAllEaf")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}
	
	err = r.setFilterKpi(shared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	}).Limit(filter.Limit).Offset(filter.CalculateOffset()).Find(&data).Error
	return
}

func (r *kpiRepoSQL) Count(ctx context.Context, filter *domain.FilterKpi) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "KpiRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterKpi(shared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.Kpi{}).Count(&total)
	count = int(total)
	
	trace.Log("count", count)
	return
}

func (r *kpiRepoSQL) Find(ctx context.Context, filter *domain.FilterKpi) (result shareddomain.Kpi, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "KpiRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterKpi(shared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *kpiRepoSQL) Save(ctx context.Context, data *shareddomain.Kpi) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "KpiRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()
	trace.Log("data", data)

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == "" {
		data.ID = uuid.NewString()
		err = shared.SetSpanToGorm(ctx, db).Create(data).Error
	} else {
		err = shared.SetSpanToGorm(ctx, db).Save(data).Error
	}
	return
}

func (r *kpiRepoSQL) Delete(ctx context.Context, data *shareddomain.Kpi) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "KpiRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = shared.SetSpanToGorm(ctx, db).Delete(data).Error
	return
}

func (r *kpiRepoSQL) setFilterKpi(db *gorm.DB, filter *domain.FilterKpi) *gorm.DB {

	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.Search != "" {
		db = db.Where("(field ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
