// Code generated by candi v1.14.3.

package repository

import (
	"context"

	"PLTD3/internal/modules/kpi/domain"
	shareddomain "PLTD3/pkg/shared/domain"
)

// KpiRepository abstract interface
type KpiRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterKpi) ([]shareddomain.Kpi, error)
	FetchAllEaf(ctx context.Context, filter *domain.FilterKpi) ([]shareddomain.Kpi, error)
	Count(ctx context.Context, filter *domain.FilterKpi) int


	
	Find(ctx context.Context, filter *domain.FilterKpi) (shareddomain.Kpi, error)
	Save(ctx context.Context, data *shareddomain.Kpi) error
	Delete(ctx context.Context, data *shareddomain.Kpi) (err error)
}
