// Code generated by candi v1.14.3.

package usecase

import (
	"context"

	"PLTD3/internal/modules/monitoring/domain"
	"PLTD3/pkg/shared/repository"
	"PLTD3/pkg/shared/usecase/common"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/factory/types"
	"github.com/golangid/candi/codebase/interfaces"
)

// MonitoringUsecase abstraction
type MonitoringUsecase interface {
	GetMonitoringReport(ctx context.Context, filter *domain.FilterMonitoring) (data []domain.ResponseMonitoring, meta candishared.Meta, err error)
	GetAllMonitoring(ctx context.Context, filter *domain.FilterMonitoring) (data []domain.ResponseMonitoring, meta candishared.Meta, err error)
	GetDetailMonitoring(ctx context.Context, id string) (data domain.ResponseMonitoring, err error)
	CreateMonitoring(ctx context.Context, data *domain.RequestMonitoring) (err error)
	UpdateMonitoring(ctx context.Context, data *domain.RequestMonitoring) (err error)
	DeleteMonitoring(ctx context.Context, id string) (err error)
}

type monitoringUsecaseImpl struct {
	sharedUsecase common.Usecase
	cache         interfaces.Cache
	repoSQL       repository.RepoSQL
	// repoMongo     repository.RepoMongo
	kafkaPub       interfaces.Publisher
}

// NewMonitoringUsecase usecase impl constructor
func NewMonitoringUsecase(deps dependency.Dependency) (MonitoringUsecase, func(sharedUsecase common.Usecase)) {
	uc := &monitoringUsecaseImpl{
		repoSQL:   repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),
	}
	if redisPool := deps.GetRedisPool(); redisPool != nil {
		uc.cache = redisPool.Cache()
	}
	if kafkaBroker := deps.GetBroker(types.Kafka); kafkaBroker != nil {
		uc.kafkaPub = kafkaBroker.GetPublisher()
	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
