// Code generated by candi v1.14.3.

package resthandler

import (
	"encoding/json"
	"io"
	"net/http"

	"github.com/labstack/echo"

	"PLTD3/internal/modules/kpi/domain"
	"PLTD3/pkg/shared/usecase"

	"github.com/golangid/candi/candihelper"
	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Mount handler with root "/"
// handling version in here
func (h *RestHandler) Mount(root *echo.Group) {
	v1Root := root.Group(candihelper.V1)

	kpi := v1Root.Group("/kpi", echo.WrapMiddleware(h.mw.HTTPBearerAuth))
	kpi.GET("", h.getAllKpi, echo.WrapMiddleware(h.mw.HTTPPermissionACL("getAllKpi")))
	kpi.GET("/eaf", h.getKpiEaf, echo.WrapMiddleware(h.mw.HTTPPermissionACL("getKpiEaf")))

	// komen dlu aja
	// kpi.GET("/:id", h.getDetailKpiByID, echo.WrapMiddleware(h.mw.HTTPPermissionACL("getDetailKpi")))
	// kpi.POST("", h.createKpi, echo.WrapMiddleware(h.mw.HTTPPermissionACL("createKpi")))
	// kpi.PUT("/:id", h.updateKpi, echo.WrapMiddleware(h.mw.HTTPPermissionACL("updateKpi")))
	// kpi.DELETE("/:id", h.deleteKpi, echo.WrapMiddleware(h.mw.HTTPPermissionACL("deleteKpi")))
}

func (h *RestHandler) getAllKpi(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "KpiDeliveryREST:GetAllKpi")
	defer trace.Finish()

	tokenClaim := candishared.ParseTokenClaimFromContext(ctx) // must using HTTPBearerAuth in middleware for this handler

	var filter domain.FilterKpi
	if err := candihelper.ParseFromQueryParam(c.Request().URL.Query(), &filter); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(c.Response())
	}

	if err := h.validator.ValidateDocument("kpi/get_all", filter); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate filter", err).JSON(c.Response())
	}

	data, meta, err := h.uc.Kpi().GetAllKpi(ctx, &filter)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	message := "Success, with your user id (" + tokenClaim.Subject + ") and role (" + tokenClaim.Role + ")"
	return wrapper.NewHTTPResponse(http.StatusOK, message, meta, data).JSON(c.Response())
}

func (h *RestHandler) getKpiEaf(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "KpiDeliveryREST:GetKpiEaf")
	defer trace.Finish()


	var filter domain.FilterKpi
	if err := candihelper.ParseFromQueryParam(c.Request().URL.Query(), &filter); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(c.Response())
	}

	data, meta, err := h.uc.Kpi().GetKpiEaf(ctx, &filter)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success", meta, data).JSON(c.Response())
}





func (h *RestHandler) getDetailKpiByID(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "KpiDeliveryREST:GetDetailKpiByID")
	defer trace.Finish()

	data, err := h.uc.Kpi().GetDetailKpi(ctx, c.Param("id"))
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success", data).JSON(c.Response())
}

func (h *RestHandler) createKpi(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "KpiDeliveryREST:CreateKpi")
	defer trace.Finish()

	body, _ := io.ReadAll(c.Request().Body)
	if err := h.validator.ValidateDocument("kpi/save", body); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(c.Response())
	}

	var payload domain.RequestKpi
	if err := json.Unmarshal(body, &payload); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	err := h.uc.Kpi().CreateKpi(ctx, &payload)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusCreated, "Success").JSON(c.Response())
}

func (h *RestHandler) updateKpi(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "KpiDeliveryREST:UpdateKpi")
	defer trace.Finish()

	body, _ := io.ReadAll(c.Request().Body)
	if err := h.validator.ValidateDocument("kpi/save", body); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(c.Response())
	}

	var payload domain.RequestKpi
	if err := json.Unmarshal(body, &payload); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	payload.ID = c.Param("id")
	err := h.uc.Kpi().UpdateKpi(ctx, &payload)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success").JSON(c.Response())
}

func (h *RestHandler) deleteKpi(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "KpiDeliveryREST:DeleteKpi")
	defer trace.Finish()

	if err := h.uc.Kpi().DeleteKpi(ctx, c.Param("id")); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success").JSON(c.Response())
}
