// Code generated by candi v1.14.3.

package repository

import (
	"context"
	
	"time"
	"github.com/google/uuid"

	"PLTD3/internal/modules/consumption/domain"
	shareddomain "PLTD3/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"PLTD3/pkg/shared"
	"strings"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type consumptionRepoSQL struct {
	readDB, writeDB *gorm.DB
}

// NewConsumptionRepoSQL mongo repo constructor
func NewConsumptionRepoSQL(readDB, writeDB *gorm.DB) ConsumptionRepository {
	return &consumptionRepoSQL{
		readDB, writeDB,
	}
}

func (r *consumptionRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterConsumption) (data []shareddomain.Consumption, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ConsumptionRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}
	
	err = r.setFilterConsumption(shared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	}).Limit(filter.Limit).Offset(filter.CalculateOffset()).Find(&data).Error
	return
}

func (r *consumptionRepoSQL) Count(ctx context.Context, filter *domain.FilterConsumption) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ConsumptionRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterConsumption(shared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.Consumption{}).Count(&total)
	count = int(total)
	
	trace.Log("count", count)
	return
}

func (r *consumptionRepoSQL) Find(ctx context.Context, filter *domain.FilterConsumption) (result shareddomain.Consumption, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ConsumptionRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterConsumption(shared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *consumptionRepoSQL) Save(ctx context.Context, data *shareddomain.Consumption) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ConsumptionRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()
	trace.Log("data", data)

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == "" {
		data.ID = uuid.NewString()
		err = shared.SetSpanToGorm(ctx, db).Create(data).Error
	} else {
		err = shared.SetSpanToGorm(ctx, db).Save(data).Error
	}
	return
}

func (r *consumptionRepoSQL) Delete(ctx context.Context, data *shareddomain.Consumption) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ConsumptionRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = shared.SetSpanToGorm(ctx, db).Delete(data).Error
	return
}

func (r *consumptionRepoSQL) setFilterConsumption(db *gorm.DB, filter *domain.FilterConsumption) *gorm.DB {

	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.Search != "" {
		db = db.Where("(field ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
