// Code generated by candi v1.14.3.

package repository

import (
	"context"
	"fmt"

	"time"

	"github.com/google/uuid"

	"PLTD3/internal/modules/business/domain"
	shareddomain "PLTD3/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"PLTD3/pkg/shared"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type businessRepoSQL struct {
	readDB, writeDB *gorm.DB
}

// NewBusinessRepoSQL mongo repo constructor
func NewBusinessRepoSQL(readDB, writeDB *gorm.DB) BusinessRepository {
	return &businessRepoSQL{
		readDB, writeDB,
	}
}


func (r *businessRepoSQL) FetchConditionUnit(ctx context.Context, filter *domain.FilterBusiness) (result []shareddomain.Business, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "BusinessRepoSQL:FetchConditionUnit")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}
	
	fmt.Println("resul",result)


// 	SELECT status, count(status) as jumlah
// FROM "pltd_pembangkit" group by status UNION ALL
// SELECT 'TOTAL' status, COUNT(status) FROM "pltd_pembangkit" 

	err = r.setFilterBusiness(shared.SetSpanToGorm(ctx, r.readDB), filter).Select(
		"status", "count(status) as jumlah").Group("status").Find(&result).Error

	return
}

func (r *businessRepoSQL) FetchAllReport(ctx context.Context, filter *domain.FilterBusiness) (data []shareddomain.BusinessReport, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "BusinessRepoSQL:FetchAllReport")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}
	
	err = r.setFilterBusiness(shared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	}).Limit(filter.Limit).Offset(filter.CalculateOffset()).Find(&data).Error
	return
}

func (r *businessRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterBusiness) (data []shareddomain.Business, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "BusinessRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}
	
	err = r.setFilterBusiness(shared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	}).Limit(filter.Limit).Offset(filter.CalculateOffset()).Find(&data).Error
	return
}

func (r *businessRepoSQL) Count(ctx context.Context, filter *domain.FilterBusiness) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "BusinessRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterBusiness(shared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.Business{}).Count(&total)
	count = int(total)
	
	trace.Log("count", count)
	return
}





// hapus jika tidak perlu
func (r *businessRepoSQL) Find(ctx context.Context, filter *domain.FilterBusiness) (result shareddomain.Business, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "BusinessRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterBusiness(shared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *businessRepoSQL) Save(ctx context.Context, data *shareddomain.Business) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "BusinessRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()
	trace.Log("data", data)

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == "" {
		data.ID = uuid.NewString()
		err = shared.SetSpanToGorm(ctx, db).Create(data).Error
	} else {
		err = shared.SetSpanToGorm(ctx, db).Save(data).Error
	}
	return
}

func (r *businessRepoSQL) Delete(ctx context.Context, data *shareddomain.Business) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "BusinessRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = shared.SetSpanToGorm(ctx, db).Delete(data).Error
	return
}

func (r *businessRepoSQL) setFilterBusiness(db *gorm.DB, filter *domain.FilterBusiness) *gorm.DB {

	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.Search != "" {
		db = db.Where("(unit ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
