// Code generated by candi v1.14.3.

package resthandler

import (
	"encoding/json"
	"io"
	"net/http"

	"github.com/labstack/echo"

	"PLTD3/internal/modules/monitoring/domain"
	"PLTD3/pkg/shared/usecase"

	"github.com/golangid/candi/candihelper"
	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
	"github.com/golangid/candi/tracer"
	"github.com/golangid/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(uc usecase.Usecase, deps dependency.Dependency) *RestHandler {
	return &RestHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Mount handler with root "/"
// handling version in here
func (h *RestHandler) Mount(root *echo.Group) {
	v1Root := root.Group(candihelper.V1)

	monitoring := v1Root.Group("/monitoring", echo.WrapMiddleware(h.mw.HTTPBearerAuth))
	monitoring.GET("", h.getAllMonitoring, echo.WrapMiddleware(h.mw.HTTPPermissionACL("getAllMonitoring")))
	monitoring.GET("/report", h.getMonitoringReport, echo.WrapMiddleware(h.mw.HTTPPermissionACL("getMonitoringReport")))

	// komen dlu aja
	// monitoring.GET("/:id", h.getDetailMonitoringByID, echo.WrapMiddleware(h.mw.HTTPPermissionACL("getDetailMonitoring")))
	// monitoring.POST("", h.createMonitoring, echo.WrapMiddleware(h.mw.HTTPPermissionACL("createMonitoring")))
	// monitoring.PUT("/:id", h.updateMonitoring, echo.WrapMiddleware(h.mw.HTTPPermissionACL("updateMonitoring")))
	// monitoring.DELETE("/:id", h.deleteMonitoring, echo.WrapMiddleware(h.mw.HTTPPermissionACL("deleteMonitoring")))
}

func (h *RestHandler) getMonitoringReport(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "MonitoringDeliveryREST:GetMonitoringReport")
	defer trace.Finish()

	var filter domain.FilterMonitoring
	if err := candihelper.ParseFromQueryParam(c.Request().URL.Query(), &filter); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(c.Response())
	}

	// if err := h.validator.ValidateDocument("monitoring/get_all", filter); err != nil {
	// 	return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate filter", err).JSON(c.Response())
	// }

	data, meta, err := h.uc.Monitoring().GetMonitoringReport(ctx, &filter)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success", meta, data).JSON(c.Response())
}

func (h *RestHandler) getAllMonitoring(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "MonitoringDeliveryREST:GetAllMonitoring")
	defer trace.Finish()

	tokenClaim := candishared.ParseTokenClaimFromContext(ctx) // must using HTTPBearerAuth in middleware for this handler

	var filter domain.FilterMonitoring
	if err := candihelper.ParseFromQueryParam(c.Request().URL.Query(), &filter); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed parse filter", err).JSON(c.Response())
	}

	if err := h.validator.ValidateDocument("monitoring/get_all", filter); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate filter", err).JSON(c.Response())
	}

	data, meta, err := h.uc.Monitoring().GetAllMonitoring(ctx, &filter)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	message := "Success, with your user id (" + tokenClaim.Subject + ") and role (" + tokenClaim.Role + ")"
	return wrapper.NewHTTPResponse(http.StatusOK, message, meta, data).JSON(c.Response())
}

func (h *RestHandler) getDetailMonitoringByID(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "MonitoringDeliveryREST:GetDetailMonitoringByID")
	defer trace.Finish()

	data, err := h.uc.Monitoring().GetDetailMonitoring(ctx, c.Param("id"))
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success", data).JSON(c.Response())
}

func (h *RestHandler) createMonitoring(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "MonitoringDeliveryREST:CreateMonitoring")
	defer trace.Finish()

	body, _ := io.ReadAll(c.Request().Body)
	if err := h.validator.ValidateDocument("monitoring/save", body); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(c.Response())
	}

	var payload domain.RequestMonitoring
	if err := json.Unmarshal(body, &payload); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	err := h.uc.Monitoring().CreateMonitoring(ctx, &payload)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusCreated, "Success").JSON(c.Response())
}

func (h *RestHandler) updateMonitoring(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "MonitoringDeliveryREST:UpdateMonitoring")
	defer trace.Finish()

	body, _ := io.ReadAll(c.Request().Body)
	if err := h.validator.ValidateDocument("monitoring/save", body); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, "Failed validate payload", err).JSON(c.Response())
	}

	var payload domain.RequestMonitoring
	if err := json.Unmarshal(body, &payload); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	payload.ID = c.Param("id")
	err := h.uc.Monitoring().UpdateMonitoring(ctx, &payload)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success").JSON(c.Response())
}

func (h *RestHandler) deleteMonitoring(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "MonitoringDeliveryREST:DeleteMonitoring")
	defer trace.Finish()

	if err := h.uc.Monitoring().DeleteMonitoring(ctx, c.Param("id")); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success").JSON(c.Response())
}
